"use strict";

const fs = require("node:fs");
const path = require("node:path");
const sharedCoreSource = fs.readFileSync(path.join(__dirname, "shared-core.js"), "utf8");
function copyq(lines, core) { return "copyq:\n" + (core ? sharedCoreSource + "\n" : "") + lines.join("\n"); }

function dispatcherBody() {
  return copyq([
    "var LEGACY_KEY = 'frequent_usage_counts'; var V2_KEY = 'frequent_usage_counts_v2'; var FREQ_MIME = 'application/x-copyq-user-frequency';",
    "function settingsObject(key, fallback) { try { var value = settings(key); return value ? JSON.parse(value) : fallback; } catch (e) { return fallback; } }",
    "var formats = dataFormats(); var textData = data(mimeText); if (!textData) abort(); var text = str(textData);",
    "var legacy = settingsObject(LEGACY_KEY, {}); var state = settingsObject(V2_KEY, { version: 2, counters: {}, clock: 0 });",
    "var routed = CopyQCore.route({ text: text, formats: formats, mimeOwner: mimeOwner, mimeHidden: mimeHidden, state: state, legacy: legacy });",
    "if (routed.action === 'passthrough') abort(); if (routed.action === 'ignored') { notification('.id', 'secret-ignore', '.title', 'Ignoring secret in the clipboard', '.message', 'SECRET_IGNORED'); ignore(); abort(); }",
    "if (routed.action === 'big') { setData(mimeOutputTab, 'BIG'); abort(); } if (routed.action === 'code') { setData(mimeOutputTab, 'Code'); abort(); }",
    "if (routed.frequency) { settings(LEGACY_KEY, JSON.stringify(routed.frequency.legacy)); settings(V2_KEY, JSON.stringify(routed.frequency.state)); }",
    "if (routed.action === 'frequent') { var originalTab = selectedTab(); tab('Frequent'); var index = -1; var i; for (i = 0; i < size(); i += 1) if (str(read(mimeText, i)) === text) { index = i; break; } if (index >= 0) { var item = getitem(index); item[FREQ_MIME] = String(routed.frequency.result.count); remove(index); var position = size(); for (i = 0; i < size(); i += 1) if (routed.frequency.result.count > Number(str(read(FREQ_MIME, i)) || 0)) { position = i; break; } insert(position, item); ignore(); tab(originalTab); abort(); } setData(FREQ_MIME, String(routed.frequency.result.count)); setData(mimeOutputTab, 'Frequent'); }",
  ], true);
}
function htmlSanitizerBody() { return copyq(["var html = str(data(mimeHtml)); if (!html) abort();", "var sanitized = CopyQCore.sanitizeHtml(html); if (sanitized === html) abort(); setData(mimeHtml, sanitized);"], true); }
function translateBody() {
  return copyq([
    "var items = selectedItemsData(); var item = items.length ? items[0] : null; var textData = item && item[mimeText] ? item[mimeText] : input(); var text = str(textData);",
    "function translationFailure(reason) { notification('.id', 'translate-en', '.title', 'Translate to English', '.message', reason); abort(); } if (!text) translationFailure('TRANSLATE_EMPTY');",
    "var programFiles = str(env('ProgramFiles')).replace(/\\\\/g, '/'); var localAppData = str(env('LOCALAPPDATA')).replace(/\\\\/g, '/'); var helper = localAppData + '/CopyQCommandSuite/translation/Invoke-CopyQAzureTranslation.ps1'; var encodedText = str(toBase64(textData)); var result = null; try { result = execute('pwsh.exe', '-NoLogo', '-NoProfile', '-NonInteractive', '-File', helper, null, encodedText); } catch (e) {} if (!result || result.exit_code !== 0) { try { result = execute(programFiles + '/PowerShell/7/pwsh.exe', '-NoLogo', '-NoProfile', '-NonInteractive', '-File', helper, null, encodedText); } catch (e2) {} }",
    "if (!result || result.exit_code !== 0) { var reason = str(result && result.stderr).replace(/\\s+$/, ''); if (!/^(?:TRANSLATE_NOT_CONFIGURED|TRANSLATE_AUTH_FAILED|TRANSLATE_REGION_FAILED|TRANSLATE_RATE_LIMITED|TRANSLATE_FAILED|TRANSLATE_EMPTY)$/.test(reason)) reason = 'TRANSLATE_FAILED'; translationFailure(reason); } var encodedTranslation = str(result.stdout).replace(/\\s+$/, ''); var translated; try { translated = str(fromBase64(encodedTranslation)); } catch (e) { translationFailure('TRANSLATE_FAILED'); } if (!translated) translationFailure('TRANSLATE_EMPTY'); copy(mimeText, translated);",
  ], false);
}
function markdownBody() { return copyq(["var text = data(mimeText); if (!text || !CopyQCore.isMarkdown(str(text))) abort();", "var appData = str(env('APPDATA')).replace(/\\\\/g, '/'); var result = null; try { result = execute('marked.cmd', null, text); } catch (e) {} if (!result || result.exit_code !== 0) { try { result = execute(appData + '/npm/marked.cmd', null, text); } catch (e2) {} }", "if (!result || result.exit_code !== 0) { notification('.id', 'markdown', '.message', 'MARKDOWN_FAILED'); abort(); } setData(mimeHtml, result.stdout);"], true); }
function pygmentsBody() { return copyq(["var text = data(mimeText); if (!text) abort();", "var script = 'import re\\nimport sys\\nfrom pygments import highlight\\nfrom pygments.lexers import guess_lexer\\nfrom pygments.formatters import HtmlFormatter\\ncode = sys.stdin.read()\\nquote = chr(34)\\nfragment = highlight(code, guess_lexer(code), HtmlFormatter(noclasses=True, nowrap=True, style=\"xcode\"))\\npattern = \"<span style=\" + quote + \"color: (#[0-9A-Fa-f]{3,6})\" + quote + \">\"\\nfragment = re.sub(pattern, lambda match: \"<font color=\" + quote + match.group(1) + quote + \">\", fragment).replace(\"</span>\", \"</font>\")\\nstyle = \"font-family: Consolas; font-size: 14px; white-space: pre-wrap; margin-top: 0px; margin-bottom: 0px;\"\\nhtml = \"<table width=\" + quote + \"100%\" + quote + \" border=\" + quote + \"0\" + quote + \" cellspacing=\" + quote + \"0\" + quote + \" cellpadding=\" + quote + \"8\" + quote + \" bgcolor=\" + quote + \"#ffffff\" + quote + \"><tr><td bgcolor=\" + quote + \"#ffffff\" + quote + \"><pre style=\" + quote + style + quote + \">\" + fragment + \"</pre></td></tr></table>\"\\nsys.stdout.write(html)';", "var result = null; try { result = execute('py.exe', '-3', '-c', script, null, text); } catch (e) {} if (!result || result.exit_code !== 0) { try { result = execute('python.exe', '-c', script, null, text); } catch (e2) {} } if (!result || result.exit_code !== 0) { notification('.id', 'pygments', '.title', 'Highlight Code', '.message', 'PYGMENTS_FAILED'); abort(); } setData(mimeHtml, result.stdout);"], false); }
function ocrBody() {
  return copyq([
    "var items = selectedItemsData(); var item = items.length ? items[0] : null; var png = item && item['image/png'] ? item['image/png'] : data('image/png'); if (!png || png.size() === 0) png = input();",
    "if (!png || png.size() === 0) { notification('.id', 'ocr', '.title', 'Copy Text in Image', '.message', 'OCR_NO_PNG'); abort(); }",
    "var programFiles = str(env('ProgramFiles')).replace(/\\\\/g, '/'); var result = null; try { result = execute('tesseract.exe', 'stdin', 'stdout', '-l', 'eng+heb', '--oem', '3', null, png); } catch (e) {} if (!result || result.exit_code !== 0) { try { result = execute(programFiles + '/Tesseract-OCR/tesseract.exe', 'stdin', 'stdout', '-l', 'eng+heb', '--oem', '3', null, png); } catch (e2) {} }",
    "if (!result || result.exit_code !== 0) { notification('.id', 'ocr', '.title', 'Copy Text in Image', '.message', 'OCR_FAILED'); abort(); } var text = str(result.stdout).replace(/\\s+$/, ''); if (!text) { notification('.id', 'ocr', '.title', 'Copy Text in Image', '.message', 'OCR_NO_TEXT'); abort(); } copy(mimeText, text);",
  ], false);
}
function copyJsonBody() { return copyq(["function out(d) { var s = str(d); return d.equals(new ByteArray(s)) ? s : { base64: toBase64(d) }; }", "var items = selectedItemsData(); for (var i in items) for (var f in items[i]) items[i][f] = out(items[i][f]); copy(JSON.stringify({ copyq_items: items }, null, 2));"], false); }
function pasteJsonBody() { return copyq(["var checked = CopyQCore.validateJsonImport(str(clipboard())); if (!checked.ok) { notification('.id', 'json', '.message', checked.reason); abort(); }", "function incoming(d) { return typeof d === 'string' ? new ByteArray(d) : fromBase64(d.base64); } for (var i in checked.value.copyq_items) { var item = checked.value.copyq_items[i]; for (var f in item) item[f] = incoming(item[f]); setItem(i, item); }"], true); }
function regexBody() { return copyq(["var query = dialog('Search'); if (!query) abort(); var checked = CopyQCore.validateRegex(query); if (!checked.ok) { notification('.id', 'regex', '.message', checked.reason); abort(); }", "var names = tab(); try { removeTab('Search'); } catch (e) {} tab('Search'); for (var t = 0; t < names.length; t += 1) { if (names[t] === 'Search') continue; tab(names[t]); for (var i = 0; i < size(); i += 1) { var item = getitem(i); if (checked.value.test(str(item[mimeText]))) { tab('Search'); insert(0, item); tab(names[t]); } } } tab('Search');"], true); }
function titleBody() { return copyq(["if (!copy()) abort(); var text = str(clipboard()); var result = CopyQCore.titleCase(text); if (result === text) abort(); copy(result); paste();"], true); }
function toggleBody() { return copyq(["if (!copy()) abort(); var text = str(clipboard()); var result = CopyQCore.toggleCase(text); if (result === text) abort(); copy(result); paste();"], true); }
function frequentBody() { return copyq(["menu('Frequent');"], false); }
function searchBody() { return copyq(["if (!copy()) abort(); var text = str(clipboard()); if (!text) abort(); var engines = [{ name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q=%s' }, { name: 'GitHub', url: 'https://github.com/search?q=%s' }]; var items = []; for (var i = 0; i < engines.length; i += 1) { var item = {}; item[mimeText] = engines[i].name; items.push(item); } var chosen = menuItems(items); if (chosen < 0) abort(); var url = engines[chosen].url.replace('%s', encodeURIComponent(text)); open(url);"], false); }
module.exports = { sharedCoreSource, dispatcherBody, htmlSanitizerBody, translateBody, markdownBody, pygmentsBody, ocrBody, copyJsonBody, pasteJsonBody, regexBody, titleBody, toggleBody, frequentBody, searchBody };
